name: Deploy to Cloudflare

on:
  push:
    branches:
      - master  # Trigger this workflow when changes are pushed to the "master" branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use a virtual machine with Ubuntu to run the workflow

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_WELFARE_PRIVATE_KEY }}

      - name: Deploy to Cloudflare
        run: ssh -o StrictHostKeyChecking=no \
              ${{ secrets.SSH_WELFARE_USER }}@${{ secrets.SSH_WELFARE_HOST }} \
              "cd /applications/czpwckszqj/public_html && git pull origin master"
